### PR TITLE
Add: Dockerfiles + std namespace + fPIC flag in src/qt

### PR DESCRIPTION
**Pull request by kaczmarj**
This PR proposes:
- adding two Dockerfiles 
- using the `std::` namespace for `fstream`, `ofstream`, and `ifstream`
- compiling code in `src/qt` with the flag `-fPIC`

The Dockerfile `docker/Dockerfile` installs all dependencies from `apt` repositories and builds and debian jessie. I chose this base image because some dependencies are not present in the `apt` repositories for newer releases. This does present issues, however, as the version of OpenGL must be similar between the container and the host to run the murfi GUI (this is testing the limits of my knowledge, so I could be wrong here). In any case, the Dockerfile `docker/source.Dockerfile` bootstraps ubuntu 18.04 and builds many dependencies from source, including the dependencies not found in the `apt` repositories of newer debian/ubuntu releases. I was able to launch the murfi gui using the image from `docker/source.Dockerfile` while running debian buster on my host. I was not able to run the `servedata.sh` script in the example, because of a connection issue. I haven't looked into that yet, but my guess is it involves some command line arguments to `docker run` and not any changes to the dockerfiles.

Moreover, I received errors (i.e., `ambiguous symbol`) when trying to compile murfi on ubuntu 18.04. I prepended `std::` to `fstream`, `ofstream`, and `ifstream` objects, and that solved the issue. The code still compiled on older gcc, as in debian jessie.

Last, I added the flag `-fPIC` to the compilation of code in `src/qt`. This was a requirement of qt in ubuntu 18.04, but this also works in older version, as in debian jessie.

For what it's worth, this PR is to be able to run murfi in a container on an ubuntu 18.04 (ish) system.

### CODE REVIEW

**Comment by satra** [comment]
@kaczmarj - let me know when you want me to review this.

**Comment by kaczmarj** [comment]
@satra - this pr is ready for review. feel free to build the docker image and convert to singularity. i pushed a docker image to `kaczmarj/murfi2` to make things easier. the container is lean at 117 MB compressed!

**Comment by kaczmarj** [comment]
clemens has confirmed that the singularity container made with the code in this PR is working as expected, including communication with psychopy.

**Comment by kaczmarj** [comment]
gentle ping @satra

**Pull request merged**
